[package]
name = "binary_search"
version = "0.1.0"
authors = ["Sander Julien-Saint-Amand <sanderjsa@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
